<CustomButtonForRationg>:
    mipmap: True
        
    allow_stretch: True      # Разрешить растяжение
    keep_ratio: False    
    color: 0,0,0,0
    size_hint: (None, None)
    background_normal: './images/buttons/rating_btn_up.png'
    background_down: './images/buttons/rating_btn_cur.png'
    size: 30,30

    # Не сохранять пропорции (картинка заполнит всю кнопку)
<CustomLayotForRating>:
    size : 150, 30